######################################################################
# Automatically generated by qmake (3.0) So. Nov. 23 21:57:54 2014
######################################################################

QT -= core gui
TEMPLATE = app
TARGET = starterbot
INCLUDEPATH += .
CONFIG += c++11
QMAKE_CXXFLAGS_DEBUG +=  -DSTARTERBOT_DEBUG

# Input
SOURCES += Bot.cpp main.cpp Parser.cpp Region.cpp SuperRegion.cpp

